services:
  - type: web
    name: ats-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn projectname.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projectname.settings
      - key: DATABASE_URL
        fromDatabase:
          name: ats-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    plan: free
    autoDeploy: true
  - type: pserv
    name: ats-worker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py runworker"
databases:
  - name: ats-db
    plan: free
