services:
  - type: web
    name: django-ats
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn projectname.wsgi:application -c gunicorn_config.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_APP_NAME
        value: ATS-Application
      - key: DATABASE_URL
        fromDatabase:
          name: django-ats-db
          property: connectionString

databases:
  - name: django-ats-db
    databaseName: ats_db
    user: ats_user
    plan: free
